version: 2.1

orbs:
  slack: circleci/slack@4

defaults: &defaults
  resource_class: small
  docker:
    - image: node:12
  working_directory: ~/rpm-parser

release_defaults: &release_defaults
  resource_class: small
  docker:
    - image: node:14
  working_directory: ~/rpm-parser

slack-fail-notify: &slack-fail-notify
  slack/notify:
    event: fail
    channel: lumos-alerts
    branch_pattern: main
    template: basic_fail_1

slack-success-notify: &slack-success-notify
  slack/notify:
    event: pass
    channel: lumos-deployments
    branch_pattern: main
    template: basic_success_1


commands:
  install_deps:
    description: Install dependencies
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-cache-{{ checksum "package.json" }}
            - v1-npm-cache-
      - run:
          name: Use snyk-main npmjs user
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-npm-cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
      - persist_to_workspace:
          root: .
          paths:
            - node_modules/

jobs:
  install_dev_deps:
    <<: *defaults
    environment:
      NODE_ENV: development
    steps:
      - install_deps

  install_prod_deps:
    <<: *defaults
    steps:
      - install_deps

  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/rpm-parser
      - run:
          name: Lint
          command: npm run lint

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/rpm-parser
      - run:
          name: Run tests
          command: npm run test

  release:
    <<: *release_defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Release on GitHub
          command: npx semantic-release@19

workflows:
  version: 2

  PR_TO_MASTER:
    jobs:
      - install_dev_deps:
          name: Install with devDependencies
          context: nodejs-install
          filters:
            branches:
              ignore:
                - master
      - lint:
          name: Lint
          context: nodejs-install
          requires:
            - Install with devDependencies
          filters:
            branches:
              ignore:
                - master
      - test:
          name: Test
          context: nodejs-install
          requires:
            - Install with devDependencies
          filters:
            branches:
              ignore:
                - master
      - install_prod_deps:
          name: Install PROD deps
          context: nodejs-install
          requires:
            - Test
            - Lint
          filters:
            branches:
              ignore:
                - master

  MERGE_TO_MASTER:
    jobs:
      - install_dev_deps:
          name: Install with devDependencies
          context: 
            - nodejs-install
            - snyk-bot-slack
          filters:
            branches:
              only:
                - master
          post-steps:
            - *slack-fail-notify
      - lint:
          name: Lint
          context: 
            - nodejs-install
            - snyk-bot-slack
          requires:
            - Install with devDependencies
          filters:
            branches:
              only:
                - master
          post-steps:
            - *slack-fail-notify
      - test:
          name: Test
          context: 
            - nodejs-install
            - snyk-bot-slack
          requires:
            - Install with devDependencies
          filters:
            branches:
              only:
                - master
          post-steps:
            - *slack-fail-notify
      - release:
          name: Release to GitHub
          context: 
            - nodejs-lib-release
            - snyk-bot-slack
          requires:
            - Install with devDependencies
            - Test
            - Lint
          filters:
            branches:
              only:
                - master
          post-steps:
            - *slack-fail-notify
            - *slack-success-notify
