version: 2.1

orbs:
  slack: circleci/slack@5
  prodsec: snyk/prodsec-orb@1
  node: circleci/node@7

defaults: &defaults
  resource_class: small
  docker:
    - image: cimg/node:20.19

slack-fail-notify: &slack-fail-notify
  slack/notify:
    event: fail
    channel: team-container-pipeline-info
    branch_pattern: main
    template: basic_fail_1

commands:
  setup_snyk_npm_user:
    steps:
      - run:
          name: Setup NPM Credentials
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc

  checkout_and_install:
    steps:
      - checkout
      - setup_snyk_npm_user
      - node/install-packages:
          cache-only-lockfile: false
          cache-path: ./node_modules
          include-branch-in-cache-key: false

jobs:
  security-scans:
    <<: *defaults
    steps:
      - checkout_and_install
      - prodsec/security_scans:
          mode: auto
          iac-scan: disabled

  install_dev_deps:
    <<: *defaults
    environment:
      NODE_ENV: development
    steps:
      - checkout_and_install

  install_prod_deps:
    <<: *defaults
    steps:
      - checkout_and_install

  lint:
    <<: *defaults
    steps:
      - checkout_and_install
      - run:
          name: Lint
          command: npm run lint

  test:
    <<: *defaults
    steps:
      - checkout_and_install
      - run:
          name: Run tests
          command: npm run test

  release:
    <<: *defaults
    steps:
      - checkout_and_install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Release on GitHub
          command: npx semantic-release@19

workflows:
  PR_TO_MAIN:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: snyk-vuln-alerts-container
          filters:
            branches:
              ignore:
                - main

      - install_dev_deps:
          name: Install with devDependencies
          context: nodejs-install
          filters:
            branches:
              ignore:
                - main
      - lint:
          name: Lint
          context: nodejs-install
          requires:
            - Install with devDependencies
          filters:
            branches:
              ignore:
                - main

      - security-scans:
          name: Security Scans
          context:
            - infrasec_container
            - prodsec-orb-runtime
          filters:
            branches:
              ignore:
                - main

      - test:
          name: Test
          context: nodejs-install
          requires:
            - Install with devDependencies
          filters:
            branches:
              ignore:
                - main
      - install_prod_deps:
          name: Install PROD deps
          context: nodejs-install
          requires:
            - Test
            - Lint
          filters:
            branches:
              ignore:
                - main

  MERGE_TO_MAIN:
    jobs:
      - install_dev_deps:
          name: Install with devDependencies
          context:
            - nodejs-install
            - snyk-bot-slack
          filters:
            branches:
              only:
                - main
          post-steps:
            - *slack-fail-notify
      - lint:
          name: Lint
          context:
            - nodejs-install
            - snyk-bot-slack
          requires:
            - Install with devDependencies
          filters:
            branches:
              only:
                - main
          post-steps:
            - *slack-fail-notify

      - security-scans:
          name: Security Scans
          context:
            - infrasec_container
            - prodsec-orb-runtime
          filters:
            branches:
              only:
                - main

      - test:
          name: Test
          context:
            - nodejs-install
            - snyk-bot-slack
          requires:
            - Install with devDependencies
          filters:
            branches:
              only:
                - main
          post-steps:
            - *slack-fail-notify
      - release:
          name: Release to GitHub
          context:
            - nodejs-lib-release
            - snyk-bot-slack
          requires:
            - Install with devDependencies
            - Test
            - Lint
            - Security Scans
          filters:
            branches:
              only:
                - main
          post-steps:
            - *slack-fail-notify
