version: 2.1

orbs:
  slack: circleci/slack@4
  prodsec: snyk/prodsec-orb@1.0
  snyk: snyk/snyk@1

defaults: &defaults
  resource_class: small
  docker:
    - image: cimg/node:18.15
  working_directory: ~/rpm-parser

release_defaults: &release_defaults
  resource_class: small
  docker:
    - image: cimg/node:18.15
  working_directory: ~/rpm-parser

slack-fail-notify: &slack-fail-notify
  slack/notify:
    event: fail
    channel: lumos-alerts
    branch_pattern: main
    template: basic_fail_1

slack-success-notify: &slack-success-notify
  slack/notify:
    event: pass
    channel: lumos-deployments
    branch_pattern: main
    template: basic_success_1


commands:
  install_deps:
    description: Install dependencies
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-cache-{{ checksum "package.json" }}
            - v1-npm-cache-
      - run:
          name: Use snyk-main npmjs user
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-npm-cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
      - persist_to_workspace:
          root: .
          paths:
            - node_modules/

jobs:
  install_dev_deps:
    <<: *defaults
    environment:
      NODE_ENV: development
    steps:
      - install_deps

  install_prod_deps:
    <<: *defaults
    steps:
      - install_deps

  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/rpm-parser
      - run:
          name: Lint
          command: npm run lint
  scan_code:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/rpm-parser
      - snyk/scan:
          command: code test
          fail-on-issues: true
          severity-threshold: high
          monitor-on-build: false
  scan_deps:
    <<: *defaults
    steps:
      - checkout
      - install_deps
      - snyk/scan:
          fail-on-issues: true
          severity-threshold: high
          monitor-on-build: false

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/rpm-parser
      - run:
          name: Run tests
          command: npm run test

  release:
    <<: *release_defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Release on GitHub
          command: npx semantic-release@19

workflows:
  version: 2

  PR_TO_MAIN:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: lumos-alerts
          filters:
            branches:
              ignore:
                - main

      - install_dev_deps:
          name: Install with devDependencies
          context: nodejs-install
          filters:
            branches:
              ignore:
                - main
      - lint:
          name: Lint
          context: nodejs-install
          requires:
            - Install with devDependencies
          filters:
            branches:
              ignore:
                - main
      - scan_code:
          name: Scan Code
          context:
            - team-lumos
          filters:
            branches:
              ignore:
                - main
      - scan_deps:
          name: Scan Dependencies
          context:
            - team-lumos
          filters:
            branches:
              ignore:
                - main

      - test:
          name: Test
          context: nodejs-install
          requires:
            - Install with devDependencies
          filters:
            branches:
              ignore:
                - main
      - install_prod_deps:
          name: Install PROD deps
          context: nodejs-install
          requires:
            - Test
            - Lint
          filters:
            branches:
              ignore:
                - main

  MERGE_TO_MAIN:
    jobs:
      - install_dev_deps:
          name: Install with devDependencies
          context: 
            - nodejs-install
            - snyk-bot-slack
          filters:
            branches:
              only:
                - main
          post-steps:
            - *slack-fail-notify
      - lint:
          name: Lint
          context: 
            - nodejs-install
            - snyk-bot-slack
          requires:
            - Install with devDependencies
          filters:
            branches:
              only:
                - main
          post-steps:
            - *slack-fail-notify

      - scan_code:
          name: Scan Code
          context:
            - team-lumos
          filters:
            branches:
              only:
                - main
      - scan_deps:
          name: Scan Dependencies
          context:
            - team-lumos
          filters:
            branches:
              only:
                - main

      - test:
          name: Test
          context: 
            - nodejs-install
            - snyk-bot-slack
          requires:
            - Install with devDependencies
          filters:
            branches:
              only:
                - main
          post-steps:
            - *slack-fail-notify
      - release:
          name: Release to GitHub
          context: 
            - nodejs-lib-release
            - snyk-bot-slack
          requires:
            - Install with devDependencies
            - Test
            - Lint
            - Scan Dependencies
            - Scan Code
          filters:
            branches:
              only:
                - main
          post-steps:
            - *slack-fail-notify
            - *slack-success-notify
