version: 2.1

defaults: &defaults
  resource_class: small
  docker:
    - image: gcr.io/snyk-main/nsolid-ubuntu:erbium
      auth:
        username: _json_key
        password: $GCLOUD_GCR_BUILDER
  working_directory: ~/rpm-parser

private_cicd_repo_auth: &private_cicd_repo_auth
  auth:
    username: _json_key
    password: $GCLOUD_GCR_BUILDER

commands:
  install_deps:
    description: Install dependencies
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-cache-{{ checksum "package-lock.json" }}
            - v1-npm-cache-
      - run:
          name: Use snyk-main npmjs user
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: v1-npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - persist_to_workspace:
          root: .
          paths:
            - node_modules/

jobs:
  install_dev_deps:
    <<: *defaults
    environment:
      NODE_ENV: development
    steps:
      - install_deps

  install_prod_deps:
    <<: *defaults
    steps:
      - install_deps

  test:
    <<: *defaults
    docker:
      - image: gcr.io/snyk-main/nsolid-ubuntu:erbium
        <<: *private_cicd_repo_auth
    steps:
      - checkout
      - attach_workspace:
          at: ~/rpm-parser
      - run:
          name: Run tests
          command: npm run test

  release:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Release on GitHub
          command: npx semantic-release

workflows:
  version: 2

  PR_TO_MASTER:
    jobs:
      - install_dev_deps:
          name: Install with devDependencies
          context: nodejs-install
          filters:
            branches:
              ignore:
                - master
      - test:
          name: Test
          context: nodejs-install
          requires:
            - Install with devDependencies
          filters:
            branches:
              ignore:
                - master
      - install_prod_deps:
          name: Install PROD deps
          context: nodejs-install
          requires:
            - Test
          filters:
            branches:
              ignore:
                - master

  MERGE_TO_MASTER:
    jobs:
      - install_dev_deps:
          name: Install with devDependencies
          context: nodejs-install
          filters:
            branches:
              only:
                - master
      - test:
          name: Test
          context: nodejs-install
          requires:
            - Install with devDependencies
          filters:
            branches:
              only:
                - master
      - install_prod_deps:
          name: Install PROD deps
          context: nodejs-install
          requires:
            - Test
          filters:
            branches:
              only:
                - master
      - release:
          name: Release to GitHub
          context: nodejs-app-release
          requires:
            - Install with devDependencies
            - Test
            - Install PROD deps
          filters:
            branches:
              only:
                - master
